# Generated by Django 2.0.1 on 2018-02-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=16, verbose_name='编码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('norms', models.CharField(blank=True, max_length=50, null=True, verbose_name='规格')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='单价')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='税')),
                ('stock_num', models.IntegerField(default=0, verbose_name='库存')),
                ('sold_num', models.IntegerField(default=0, verbose_name='已售出')),
                ('batch', models.CharField(blank=True, max_length=100, null=True, verbose_name='生产批号')),
                ('reg_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='注册证号')),
                ('producers', models.CharField(blank=True, max_length=255, null=True, verbose_name='生产企业')),
                ('valid', models.CharField(blank=True, max_length=255, null=True, verbose_name='有效期')),
                ('storage_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('product_type', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'medical_product',
                'ordering': ['-id'],
            },
        ),
    ]
